name: capsulas_embalaje
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ^3.12.2

dependencies:
  chewie: ^1.14.1
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^34.1.30
  video_player: ^2.8.6 
  video_player_win: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/CapsulasEmbalador/
    - assets/videos/CapsulasErrores/
    - assets/videos/CapsulasSupervisor/
    - assets/videos/CapsulasEmbaladorPrivilegios/
    - assets/Documentos/ManualEmbalador.pdf
    - assets/Documentos/ManualSupervisor.pdf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mamutv.png"
  min_sdk_version: 21